version: 2
jobs:
  testFeatureBranches:
    resource_class: small
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build react application Docker image
          command: |
            docker build -t kellydouglass/react-front-circleci-complex -f ./react-front-circleci-complex/Dockerfile.dev ./react-front-circleci-complex
      - run:
          name: Run react Tests
          command: |
            docker run -e CI=true kellydouglass/react-front-circleci-complex npm run test
            
workflows:
  version: 2
  build_test:
    jobs:
      - testFeatureBranches:
          filters:
            branches:
              ignore:
                - main
                - master